### ISSUE TITLE
video.mov 

### ISSUE THREAD

**Issue by keks777** [ataylor32/demo-html5-transparent-video#1]
how was this video created? using ffmpeg?

**Comment by ataylor32** [comment]
Sorry for the delay; I meant to get back to you sooner.

I had the video in the Apple ProRes 4444 format (if I recall correctly). To convert it into HEVC format, I used a Mac to go to the video file in Finder, right-clicked it, and chose "Encode Selected Video Files". An "Encode Media" window appeared. I set the "Setting" dropdown menu to one of the "HEVC" options, checked the "Preserve Transparency" checkbox, and then clicked the "Continue" button.

**Comment by keks777** [comment]
Thx for the response :)

Чт, 19 нояб. 2020 г. в 00:29, Adam <notifications@github.com>:
